# Generated by Django 4.0.4 on 2022-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=20, null=True)),
                ('pul', models.CharField(max_length=20, null=True)),
                ('oxy', models.CharField(max_length=20, null=True)),
                ('timee', models.DateTimeField()),
            ],
        ),
    ]
